data:
    dataset: "uci"
    dir: "bostonHousing"
    n_splits: 20
    num_workers: 0
    one_hot_encoding: True
    normalize_x: True
    normalize_y: True
    data_root: "/home/user/daojun/Data/TS/UCI_Datasets"

model:
    type: "simple"
    data_dim: 14
    x_dim: 13
    y_dim: 1
    z_dim: 2
    cat_x: True
    feature_dim: 128
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: cosine  # cosine linear
    beta_start: 0.0001
    beta_end: 0.02
    timesteps: 10
    vis_step: 100
    num_figs: 10
    conditioning_signal: "NN"
    nonlinear_guidance:
        pre_train: True
        joint_train: False
        n_pretrain_epochs: 1000
        logging_interval: 10
        hid_layers: [128] # [100, 50]
        use_batchnorm: False
        negative_slope: 0.01
        dropout_rate: 0.2
        apply_early_stopping: False   ### 修改成False了
        n_pretrain_max_epochs: 1000
        train_ratio: 0.6  # for splitting original train into train and validation set for hyperparameter tuning
        patience: 5
        delta: 0  # hyperparameter for improvement measurement in the early stopping scheme

training:
    batch_size: 32
    n_epochs: 5000
    n_iters: 100000
    snapshot_freq: 1000000000
    logging_freq: 2000
    validation_freq: 20000
    image_folder: 'training_image_samples'


testing:
    batch_size: 64
    n_z_samples: 4000
    sampling_size: 1 #1000
    last_only: True
    plot_freq: 5
    image_folder: 'testing_image_samples'
    n_bins: 10
    compute_metric_all_steps: False # 改成False了
    mean_t: 0
    coverage_t: 0
    nll_t: 0
    trimmed_mean_range: [0.0, 100.0]
    PICP_range: [2.5, 97.5]
    make_plot: False
    squared_plot: False
    plot_true: False
    plot_gen: False
    fig_size: [8, 5]

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0

aux_optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0